name: CSE404_h200
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu126
    - torch_geometric
