name: CSE404_h200
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - pyvis
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu126
    - torch_geometric

# Choose CUDA version before install, if not then type `cpu`
# https://download.pytorch.org/whl/...